spring:
  profiles:
    include: dev,db,mq,redis

server:
  port: 8080
  connection:
    timeout: 7200
  servlet:
    context-path: /sbhjj

mybatis:
  mapper-locations: classpath:mapping/*.xml

pagehelper:
  helper-dialect: mysql
  reasonable: true
  upport-methods-arguments: true
  params: count=countSql




